export const clerkAppearance = {
  variables: {
    colorPrimary: "#ff6a00",
    colorText: "#1d2738",
    colorBackground: "#ffffff",
    colorInputBackground: "#ffffff",
    colorInputText: "#1d2738",
    colorNeutral: "#d7dce5",
    borderRadius: "16px",
    fontFamily: "Alibaba_B2B_Sans, Inter, sans-serif",
  },
  elements: {
    rootBox: "w-full",
    cardBox: "w-full shadow-none",
    card: "w-full rounded-[24px] border border-[#ebe4da] bg-white px-5 py-6 shadow-[0_18px_44px_rgba(17,24,39,0.08)] sm:rounded-[32px] sm:px-8 sm:py-9 sm:shadow-[0_24px_70px_rgba(17,24,39,0.08)]",
    headerTitle: "hidden",
    headerSubtitle: "hidden",
    socialButtonsBlockButton: "h-11 rounded-[14px] border border-[#d7dce5] shadow-none transition hover:border-[#ff6a00] hover:bg-[#fff7f1]",
    socialButtonsBlockButtonText: "text-[14px] font-semibold text-[#222]",
    dividerLine: "bg-[#ebe4da]",
    dividerText: "text-[12px] font-semibold uppercase tracking-[0.2em] text-[#98a2b3]",
    formFieldLabel: "text-[13px] font-semibold text-[#344054]",
    formFieldInput: "h-11 rounded-[14px] border border-[#d7dce5] px-4 text-[14px] shadow-none outline-none focus:border-[#ff6a00]",
    formButtonPrimary: "h-11 rounded-full bg-[#ff6a00] px-5 text-[14px] font-semibold text-white shadow-none transition hover:bg-[#eb6100]",
    footerActionLink: "font-semibold text-[#ff6a00] transition hover:text-[#d95a00]",
    identityPreviewText: "text-[#667085]",
    identityPreviewEditButton: "font-semibold text-[#ff6a00] transition hover:text-[#d95a00]",
    otpCodeFieldInput: "h-11 rounded-[14px] border border-[#d7dce5] shadow-none focus:border-[#ff6a00]",
    formFieldAction: "font-semibold text-[#ff6a00] transition hover:text-[#d95a00]",
    alertText: "text-[13px]",
    alertClerkError: "rounded-[16px] bg-[#fff1f2] px-4 py-3 font-medium text-[#b42318] ring-1 ring-[#f5c2c7]",
    footer: "hidden",
  },
} as const;