import type { AdminOrderParcelSnapshot } from "@/lib/admin-order-parcel";
import type { AdminOrderRecord } from "@/lib/admin-data";
import type { SourcingOrder } from "@/lib/alibaba-sourcing";

const sampleCreatedAt = "2026-04-28T10:15:00.000Z";
const sampleUpdatedAt = "2026-04-29T09:40:00.000Z";
const sampleMetaKey = "__afripaySourcingMeta";

export const previewAdminOrderRecord: AdminOrderRecord = {
  id: "preview-order-001",
  orderNumber: "CMD-2026-0042",
  documentNumber: "BL-2026-0042",
  pdfExportsCount: 2,
  displayNumber: 36,
  customerName: "Kokou Mensah",
  customerEmail: "kokou.mensah@example.com",
  customerPhone: "+22890112233",
  productTitle: "Montre connectée X9 Pro",
  shippingMethod: "air",
  paymentStatus: "paid",
  status: "relay_ready",
  countryCode: "TG",
  addressLine: "Agoe Assiyeye, Lome, Maritime",
  totalPriceFcfa: 84500,
  totalUsd: 138.52,
  createdAt: sampleCreatedAt,
  href: "/preview/admin-orders/preview-order-001",
  parcelHref: "/preview/admin-orders/preview-order-001",
};

export const previewSourcingOrder: SourcingOrder = {
  id: "preview-order-001",
  orderNumber: "CMD-2026-0042",
  userId: "preview-user-001",
  customerName: "Kokou Mensah",
  customerEmail: "kokou.mensah@example.com",
  customerPhone: "+22890112233",
  googleMapsUrl: "https://maps.google.com/?q=6.1725,1.2314",
  addressLine1: "Agoe Assiyeye, rue 125",
  addressLine2: "Près du carrefour NOPATO",
  city: "Lome",
  state: "Maritime",
  postalCode: "01BP100",
  countryCode: "TG",
  shippingMethod: "air",
  shippingCostFcfa: 12500,
  cartProductsTotalFcfa: 72000,
  totalPriceFcfa: 84500,
  totalWeightKg: 1.8,
  totalVolumeCbm: 0.03,
  status: "relay_ready",
  freightStatus: "verified",
  supplierOrderStatus: "created",
  paymentStatus: "paid",
  paymentProvider: "moneroo",
  paymentCurrency: "XOF",
  alibabaTradeIds: ["1958473625012345678"],
  monerooPaymentId: "MON-458221",
  monerooCheckoutUrl: "https://checkout.example.test/pay/MON-458221",
  monerooPaymentStatus: "paid",
  monerooInitializedAt: sampleCreatedAt,
  monerooVerifiedAt: sampleUpdatedAt,
  paidAt: "2026-04-28T10:20:00.000Z",
  notes: "Client souhaite confirmation WhatsApp avant remise au relais.",
  createdAt: sampleCreatedAt,
  updatedAt: sampleUpdatedAt,
  items: [
    {
      slug: "smartwatch-x9-pro",
      title: "Montre connectée X9 Pro",
      quantity: 1,
      selectedVariants: { couleur: "Noir", bracelet: "Silicone" },
      selectionLabel: "Noir · Silicone",
      requiredVariantLabels: [],
      missingVariantLabels: [],
      variantSelectionComplete: true,
      supplierSkuId: "SKU-9981",
      supplierSkuCode: "X9PRO-BLK",
      weightKg: 1.8,
      volumeCbm: 0.03,
      supplierPriceFcfa: 52000,
      marginMode: "fixed",
      marginValue: 20000,
      marginAmountFcfa: 20000,
      finalUnitPriceFcfa: 72000,
      finalLinePriceFcfa: 72000,
      image: "/products/placeholder.svg",
    },
  ],
  supplierOrderPayload: {
    automation: {
      alibabaPostPayment: {
        lastProcessedAt: sampleUpdatedAt,
        lastTrigger: "admin-order-manual",
        trades: [
          {
            tradeId: "1958473625012345678",
            paymentRequestedAt: sampleCreatedAt,
            paymentRequestStatus: "requested",
            paymentRequestMessage: "Lien fournisseur généré.",
            payUrl: "https://trade.alibaba.com/order_detail.htm?tradeId=1958473625012345678",
            paymentResultCheckedAt: sampleUpdatedAt,
            paymentResultStatus: "paid",
            paymentResultMessage: "Commande fournisseur réglée.",
            trackingCheckedAt: sampleUpdatedAt,
            trackingStatus: "success",
            trackingMessage: "Colis reçu au hub Guangzhou.",
            tracking: [
              {
                trackingNumber: "YT9988776655",
                carrier: "YunExpress",
                eventCount: 4,
                currentEventCode: "IN_TRANSIT",
                trackingUrl: "https://www.17track.net/en",
              },
            ],
          },
        ],
      },
    },
    [sampleMetaKey]: {
      workflow: {
        routeType: "afripay-final-mile",
        freeDeliveryEligible: false,
        supplierDeliveryAddressRole: "afripay-agent",
        relayPointAddress: "Relais AfriPay Agoe Assiyeye",
        relayPointLabel: "Retrait au relais principal",
        availableForPickupAt: sampleUpdatedAt,
        deliveredToAgentAt: "2026-04-29T08:10:00.000Z",
        proofs: [
          {
            id: "proof-1",
            role: "supplier_to_agent",
            title: "Réception colis fournisseur",
            note: "Carton intact à l’arrivée.",
            mediaUrl: "/products/placeholder.svg",
            actorLabel: "Hub Guangzhou",
            createdAt: sampleUpdatedAt,
          },
        ],
      },
      parcel: {
        note: "Carton petit format, prêt pour retrait.",
        photos: [
          {
            id: "parcel-photo-1",
            url: "/products/placeholder.svg",
            label: "Photo colis au relais",
            createdAt: sampleUpdatedAt,
          },
        ],
        updatedAt: sampleUpdatedAt,
      },
      manualFulfillment: {
        enabled: true,
        statusLabel: "Disponible au relais",
        checkpointLabel: "Relais AfriPay confirmé",
        checkpointNote: "Le client peut récupérer le colis aujourd’hui avant 18h.",
        agentName: "Equipe AfriPay Lome",
        agentPhone: "+22870000000",
        etaLabel: "Disponible maintenant",
        lastUpdatedAt: sampleUpdatedAt,
      },
      deliveryProfile: {
        mode: "direct",
        useExactPosition: true,
        googleMapsUrl: "https://maps.google.com/?q=6.1725,1.2314",
        detectedCountryCode: "TG",
        detectedCountryLabel: "Togo",
        detectedCity: "Lome",
      },
      manychat: {
        subscriberId: "mc-1001",
        flowId: "flow-55",
        paidTagId: "tag-paid-1",
        logisticsLastSentAt: sampleUpdatedAt,
      },
      deliveryNoteExports: [
        {
          id: "export-1",
          documentNumber: "BL-2026-0042",
          disposition: "inline",
          exportedAt: sampleUpdatedAt,
          exportedByEmail: "ops@afripay.space",
        },
      ],
    },
  },
};

export const previewParcelSnapshot: AdminOrderParcelSnapshot = {
  parcelHref: "/preview/admin-orders/preview-order-001",
  printHref: "/preview/admin-orders/preview-order-001",
  totalItems: 1,
  totalUnits: 1,
  supplierNames: ["Shenzhen Time Tech"],
  manualNote: "Colis prêt pour retrait, contrôle qualité effectué.",
  manualPhotos: [
    {
      id: "manual-photo-1",
      url: "/products/placeholder.svg",
      label: "Colis scellé",
      source: "manual",
      createdAt: sampleUpdatedAt,
    },
  ],
  proofMedia: ["/products/placeholder.svg"],
  primaryGallery: ["/products/placeholder.svg"],
  photoEntries: [
    {
      id: "manual-photo-1",
      url: "/products/placeholder.svg",
      label: "Colis scellé",
      source: "manual",
      createdAt: sampleUpdatedAt,
    },
  ],
  sourceLinks: ["https://www.aliexpress.com/item/1005000000000000.html"],
  routing: {
    routeLabel: "AfriPay final mile",
    destinationLabel: "Lome, Togo",
    pickupLabel: "Relais Agoe Assiyeye",
    pickupAddress: "Rue 125, Agoe Assiyeye, Lome",
    pickupReadyAt: sampleUpdatedAt,
    clientAddressLines: [
      "Agoe Assiyeye, rue 125",
      "Près du carrefour NOPATO",
      "Lome, Maritime, Togo",
    ],
  },
  items: [
    {
      slug: "smartwatch-x9-pro",
      title: "Montre connectée X9 Pro",
      quantity: 1,
      selectionLabel: "Noir · Silicone",
      image: "/products/placeholder.svg",
      gallery: ["/products/placeholder.svg"],
      sourceProductId: "1005000000000000",
      sourceUrl: "https://www.aliexpress.com/item/1005000000000000.html",
      supplierName: "Shenzhen Time Tech",
      supplierLocation: "Guangdong, China",
      packaging: "Boîte individuelle",
      itemWeightGrams: 1800,
      overview: ["Écran AMOLED", "Bluetooth 5.3", "Autonomie 7 jours"],
      specs: [
        { label: "Couleur", value: "Noir" },
        { label: "Bracelet", value: "Silicone" },
      ],
    },
  ],
};