export const clerkAppearance = {
  variables: {
    colorPrimary: "#ff6a00",
    colorText: "#1d2738",
    colorTextSecondary: "#667085",
    colorBackground: "#ffffff",
    colorInputBackground: "#ffffff",
    colorInputText: "#1d2738",
    borderRadius: "18px",
    fontFamily: "var(--font-geist-sans)",
  },
  elements: {
    rootBox: "w-full",
    card: "w-full rounded-[24px] border border-[#ebe4da] bg-white p-0 shadow-none",
    cardBox: "w-full shadow-none",
    header: "hidden",
    socialButtonsBlockButton: "hidden",
    formButtonPrimary: "h-12 rounded-[16px] bg-[#ff6a00] text-[15px] font-semibold text-white shadow-none hover:bg-[#eb6100]",
    formFieldInput: "h-12 rounded-[16px] border border-[#d7dce5] bg-white px-4 text-[15px] text-[#1d2738] shadow-none focus:border-[#ff6a00] focus:ring-0",
    formFieldLabel: "text-[14px] font-semibold text-[#344054]",
    footerActionLink: "font-semibold text-[#ff6a00] hover:text-[#d95a00]",
    identityPreviewText: "text-[#344054]",
    identityPreviewEditButton: "text-[#ff6a00] hover:text-[#d95a00]",
    dividerText: "text-[12px] uppercase tracking-[0.14em] text-[#98a2b3]",
    dividerLine: "bg-[#eceff4]",
    alert: "rounded-[16px] px-4 py-3 text-[14px]",
    alertText: "text-[14px] leading-6",
    alertClerkError: "rounded-[16px] bg-[#fff1f2] px-4 py-3 font-medium text-[#b42318] ring-1 ring-[#f5c2c7]",
    footer: "hidden",
    formResendCodeLink: "font-semibold text-[#ff6a00] hover:text-[#d95a00]",
    otpCodeFieldInput: "h-12 rounded-[16px] border border-[#d7dce5] text-[18px] shadow-none focus:border-[#ff6a00] focus:ring-0",
  },
};

export const authPageClerkAppearance = {
  ...clerkAppearance,
  elements: {
    ...clerkAppearance.elements,
    rootBox: "mx-auto w-full max-w-[460px] min-w-0",
    card: "w-full border-0 bg-transparent p-0 shadow-none",
    cardBox: "w-full shadow-none",
    header: "hidden",
    socialButtonsBlockButton: "hidden",
    socialButtonsBlockButtonText: "text-[15px] font-semibold text-[#111827]",
    socialButtonsProviderIcon__google: "scale-110",
    socialButtonsProviderIcon__apple: "scale-110",
    dividerRow: "my-2",
    dividerText: "text-[11px] uppercase tracking-[0.18em] text-[#98a2b3]",
    dividerLine: "bg-[#edf1f5]",
    formButtonPrimary: "min-h-[52px] rounded-[18px] bg-[#1f2937] px-4 text-[15px] font-semibold text-white shadow-none transition hover:bg-[#111827]",
    formField: "min-w-0 space-y-1.5",
    formFieldInput: "min-h-[52px] rounded-[18px] border border-[#d7dce5] bg-white px-4 text-[15px] text-[#1d2738] shadow-none focus:border-[#ff6a00] focus:ring-0",
    formFieldLabel: "min-w-0 flex-1 text-[13px] font-semibold leading-5 text-[#344054]",
    formFieldLabelRow: "flex flex-wrap items-center justify-between gap-x-3 gap-y-1",
    formFieldAction: "text-right text-[12px] font-semibold leading-5 text-[#ff6a00] whitespace-normal hover:text-[#d95a00] sm:text-[13px]",
    formFieldAction__forgotPassword: "text-right text-[12px] font-semibold leading-5 text-[#ff6a00] whitespace-normal hover:text-[#d95a00] sm:text-[13px]",
    formFieldRow: "gap-2 min-w-0",
    form: "space-y-4",
    footer: "hidden",
    footerAction: "hidden",
    footerActionLink: "font-semibold text-[#ff6a00] hover:text-[#d95a00]",
    identityPreview: "rounded-[18px] border border-[#e8edf4] bg-[#f8fafc]",
    formHeaderTitle: "hidden",
    formHeaderSubtitle: "hidden",
    alert: "hidden",
    alertText: "hidden",
    alertClerkError: "hidden",
  },
};
