export const clerkAppearance = {
  variables: {
    colorPrimary: "#ff6a00",
    colorText: "#1d2738",
    colorTextSecondary: "#667085",
    colorBackground: "#ffffff",
    colorInputBackground: "#ffffff",
    colorInputText: "#1d2738",
    borderRadius: "18px",
    fontFamily: "var(--font-geist-sans)",
  },
  elements: {
    rootBox: "w-full",
    card: "w-full rounded-[24px] border border-[#ebe4da] bg-white p-0 shadow-none",
    cardBox: "w-full shadow-none",
    header: "hidden",
    socialButtonsBlockButton: "hidden",
    formButtonPrimary: "h-12 rounded-[16px] bg-[#ff6a00] text-[15px] font-semibold text-white shadow-none hover:bg-[#eb6100]",
    formFieldInput: "h-12 rounded-[16px] border border-[#d7dce5] bg-white px-4 text-[15px] text-[#1d2738] shadow-none focus:border-[#ff6a00] focus:ring-0",
    formFieldLabel: "text-[14px] font-semibold text-[#344054]",
    footerActionLink: "font-semibold text-[#ff6a00] hover:text-[#d95a00]",
    identityPreviewText: "text-[#344054]",
    identityPreviewEditButton: "text-[#ff6a00] hover:text-[#d95a00]",
    dividerText: "text-[12px] uppercase tracking-[0.14em] text-[#98a2b3]",
    dividerLine: "bg-[#eceff4]",
    alert: "rounded-[16px] px-4 py-3 text-[14px]",
    alertText: "text-[14px] leading-6",
    alertClerkError: "rounded-[16px] bg-[#fff1f2] px-4 py-3 font-medium text-[#b42318] ring-1 ring-[#f5c2c7]",
    footer: "hidden",
    formResendCodeLink: "font-semibold text-[#ff6a00] hover:text-[#d95a00]",
    otpCodeFieldInput: "h-12 rounded-[16px] border border-[#d7dce5] text-[18px] shadow-none focus:border-[#ff6a00] focus:ring-0",
  },
};

export const authPageClerkAppearance = {
  ...clerkAppearance,
  elements: {
    ...clerkAppearance.elements,
    rootBox: "mx-auto w-full max-w-[480px]",
    card: "w-full rounded-[24px] border border-[#d7dce5] bg-white p-0 shadow-[0_20px_48px_rgba(17,24,39,0.08)]",
    cardBox: "w-full rounded-[24px] shadow-none",
    header: "px-6 pt-6 text-center",
    headerTitle: "text-[22px] font-bold text-[#111827]",
    headerSubtitle: "mt-2 text-[14px] leading-6 text-[#667085]",
    socialButtonsBlockButton: "flex h-12 rounded-[8px] border border-[#d8dde6] bg-white px-4 text-[14px] font-semibold text-[#111827] shadow-none transition hover:border-[#c2c9d6] hover:bg-[#fafbfc]",
    socialButtonsBlockButtonText: "text-[15px] font-semibold text-[#111827]",
    socialButtonsProviderIcon__google: "scale-110",
    socialButtonsProviderIcon__apple: "scale-110",
    dividerRow: "my-4",
    dividerText: "text-[11px] uppercase tracking-[0.18em] text-[#98a2b3]",
    formButtonPrimary: "h-12 rounded-[8px] bg-[#242936] text-[15px] font-semibold text-white shadow-none transition hover:bg-[#1c212c]",
    formFieldInput: "h-12 rounded-[8px] border border-[#d7dce5] bg-white px-4 text-[15px] text-[#1d2738] shadow-none focus:border-[#242936] focus:ring-0",
    formFieldLabel: "text-[13px] font-semibold text-[#344054]",
    footer: "px-6 pb-6",
    footerAction: "text-[13px] text-[#667085]",
    footerActionLink: "font-semibold text-[#ff6a00] hover:text-[#d95a00]",
  },
};
